### ISSUE TITLE
[Feature Request] Tables in presentations

### ISSUE THREAD

**Issue by fharding1** [unidoc/unioffice#293]
There's currently no way to insert tables into presentations. It would be nice to be able to do that.

**Comment by mec07** [comment]
This is a feature that we really want as well. It would be great to be able to insert them at the table template placeholder.

**Comment by mec07** [comment]
@gunnsth @nkryuchkov I've been looking at the library, trying to work out why tables aren't a trivial extension to `presentation`. It seems like the `pml` schema is missing tables. I don't know why, because they exist within the open office xml schemas: http://officeopenxml.com/drwTable.php

How exactly are the schema files generated? At the top of each schema file it says: 
```
// DO NOT EDIT: generated by gooxml ECMA-376 generator
```
What is the ECMA-376 generator and how can I use it to try to generate the tables part of the `pml` schema? Thanks! :)

**Comment by gunnsth** [comment]
This is addressed in v1.6.0, see also example
https://github.com/unidoc/unioffice-examples/blob/master/presentation/tables/main.go

**Comment by gunnsth** [comment]
Closing as this is already supported.
